# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serra < Formula
  desc "serra - Personal Magic: The Gathering Collection Tracker "
  homepage "https://github.com/noqqe/serra"
  version "3.18.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/noqqe/serra/releases/download/3.18.4/serra_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9d29ea715766abff74fffcb0a822cca2a223899c97b7eaa6a8c7c988f3969bc5"

      def install
        bin.install "serra"
      end
    end
    on_arm do
      url "https://github.com/noqqe/serra/releases/download/3.18.4/serra_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "be395d59a7b7d1b19bc51c109bd22d8b81e73b532732cb67848e1ccf2a282950"

      def install
        bin.install "serra"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noqqe/serra/releases/download/3.18.4/serra_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "76479ece2523be9ad61949c7ae276ca5c91e44dbebd32eaff511928bb9a16ed5"

        def install
          bin.install "serra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noqqe/serra/releases/download/3.18.4/serra_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7290547b1649905e14b38f52402e95319feef597b989a5861298d00d76d5b75d"

        def install
          bin.install "serra"
        end
      end
    end
  end

  test do
    system "#{bin}/serra --version"
  end
end
