# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump - dumb version bump"
  homepage "https://github.com/noqqe/bump"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/bump/releases/download/0.8.0/bump_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7816e22b87c3a8aa5963d9206d3c6a6e2fecb7c5b199f243049b7800c9ceef83"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/bump/releases/download/0.8.0/bump_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0ea2beb53a7fedbfc935e3d6385105565f7054ec9280a398ba601301534452e2"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/bump/releases/download/0.8.0/bump_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "848af430f19da7cfd8f197f690b1f7547f5e918340892b4d7ea7b6888291c08a"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/bump/releases/download/0.8.0/bump_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "893e63f7d29adba02fd839f422e650759056f88514fe1f4ff2097eb8075eabd1"

      def install
        bin.install "bump"
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
