# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump - dumb version bump"
  homepage "https://github.com/noqqe/bump"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/bump/releases/download/1.0.1/bump_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b515c57c3c659b1bbed38baea9aadcb7d4c20e2e6fbad38323c58ae358aaed46"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/bump/releases/download/1.0.1/bump_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "637ad280b32edc1053742056a2912122e59738a74f68cc5b2158ef50f2098031"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/bump/releases/download/1.0.1/bump_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "bb63f93b4c21aca4cd1d35587581fd50ac9c2fc2d44ecec42d7c6f84d27562a0"
      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/bump/releases/download/1.0.1/bump_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8dfec6055594cf66dc1db0a9215bc2dfdd0e08313eceb6f99ca5f0585db76d36"
      def install
        bin.install "bump"
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
