# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump - dumb version bump"
  homepage "https://github.com/noqqe/bump"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/bump/releases/download/0.6.0/bump_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6be312f001309709dcfaa3a4c708fd0a9c521f03ee46cc4eb676ff41751edeb0"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/bump/releases/download/0.6.0/bump_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f12f81c97ff94fe6c06ce05e9942a9c613a3b16e5315b63d4e732890bf96405a"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/bump/releases/download/0.6.0/bump_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "09cf225ffae937fd1193e1f7ea457b17730840e46d521fc9772fd010621607dd"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/bump/releases/download/0.6.0/bump_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0677d22d938ec93a1cfe22bac26d49e255489722d657a1cad78f7b2ab64576c"

      def install
        bin.install "bump"
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
