# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipcalc < Formula
  desc "ipcalc - written in go"
  homepage "https://github.com/noqqe/ipcalc"
  version "0.3.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/noqqe/ipcalc/releases/download/v0.3.1/ipcalc_0.3.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "ae0c40801b4f19e4d8bb8236bbbbf2c0aee4346876ba7ba1bed3fcf60989829a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/noqqe/ipcalc/releases/download/v0.3.1/ipcalc_0.3.1_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "f41ddb36e5768612875619493670ca709df392e87c5825d954d28f62df56ce3d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/noqqe/ipcalc/releases/download/v0.3.1/ipcalc_0.3.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "c3bbf6bb30896b36c707a3ed57230bcf19f6e4b6282998f1b229f995767b1fc7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/noqqe/ipcalc/releases/download/v0.3.1/ipcalc_0.3.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "5e71503e7277c3efa6c6949097a43def92f568500fc20f40646816e4db22c71a"
  end

  conflicts_with "ipcalc"

  def install
    bin.install "ipcalc"
  end

  test do
    system "#{bin}/ipcalc --version"
  end
end
