# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipcalc < Formula
  desc "ipcalc - written in go"
  homepage "https://github.com/noqqe/ipcalc"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/ipcalc/releases/download/0.4.3/ipcalc_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c43cad93dbbd3f69dc4bb0d151620b49c50ef13a67e4f24a3c86336c514d73e0"

      def install
        bin.install "ipcalc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/ipcalc/releases/download/0.4.3/ipcalc_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c77bef3929cc30810152a4917a2948f861de349c8105f5a97d05d2034011ac6e"

      def install
        bin.install "ipcalc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/ipcalc/releases/download/0.4.3/ipcalc_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0c23428ec5fea5b214aebc97718ec70da8a03c5e71647374bdb55f948c308516"

      def install
        bin.install "ipcalc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/ipcalc/releases/download/0.4.3/ipcalc_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3fdd6bec0fb8de03b8d6222ff07f5f93690e0f33923a49d24232d83156a430c4"

      def install
        bin.install "ipcalc"
      end
    end
  end

  conflicts_with "ipcalc"

  test do
    system "#{bin}/ipcalc --version"
  end
end
