# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serra < Formula
  desc "serra - Personal Magic: The Gathering Collection Tracker "
  homepage "https://github.com/noqqe/serra"
  version "3.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/serra/releases/download/3.12.0/serra_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5cc33e9f86d5c4a986e62f5f3768f15bd4d1bbc357207a1ac434a2bb90229409"

      def install
        bin.install "serra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/serra/releases/download/3.12.0/serra_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "65d24e3f717ea1af9cdbed00bdba0c0d5ce1215e5b0b6f63fe5c13eab46499fd"

      def install
        bin.install "serra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/serra/releases/download/3.12.0/serra_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1aa7ed009232325b06cea30ba68e6d49f82a3a816c35bdbc574c6d9672490bd1"

      def install
        bin.install "serra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/serra/releases/download/3.12.0/serra_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3928f58d6f8e4340774391b5f97cc2217af01f92a8678deecc71b53abcd96ee3"

      def install
        bin.install "serra"
      end
    end
  end

  test do
    system "#{bin}/serra --version"
  end
end
