# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tijd < Formula
  desc "time tool for working remote with the world"
  homepage "https://github.com/noqqe/tijd"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/tijd/releases/download/v0.0.5/tijd_0.0.5_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9e262c22226d4e53e5f78c62f09329c4fbd8c0e293d143aae68770a06f3b8a22"

      def install
        bin.install "tijd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/tijd/releases/download/v0.0.5/tijd_0.0.5_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fab2481561a583286730ae004774b9e3d7ff566572817f9b2a6540a49888077c"

      def install
        bin.install "tijd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/tijd/releases/download/v0.0.5/tijd_0.0.5_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "df0c7b35ca11d9d200cddb3d9e7cfaa7057bf5423eecabe777145dbaf4fa3192"

      def install
        bin.install "tijd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/tijd/releases/download/v0.0.5/tijd_0.0.5_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "361626d6bb1be8a5e21be19e33d4ce4ec67d55cb2a9d0cbbab4916328731c163"

      def install
        bin.install "tijd"
      end
    end
  end
end
