# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typist < Formula
  desc "typist - I wrote a typing trainer to get into my ortholinear keyboard"
  homepage "https://github.com/noqqe/typist"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/typist/releases/download/2.0.0/typist_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4fa005035c3e8008c7beace507950bde32fb189972583e69f9c4c60e1dd1adde"

      def install
        bin.install "typist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/typist/releases/download/2.0.0/typist_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d7738cc683cf91d2e07178d72e3fc4eb6b665c504de05c8805e6d2d9d35e2b78"

      def install
        bin.install "typist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/typist/releases/download/2.0.0/typist_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5745bbe5b9ea1c0990f1a431e3d219c94de83646e78169607e2411f06aa7a723"

      def install
        bin.install "typist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/typist/releases/download/2.0.0/typist_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "dde050c1da43617d2355c8e0cd8b0f62c8dc7f94c5ea82998cf55c8cbff1a554"

      def install
        bin.install "typist"
      end
    end
  end

  test do
    system "#{bin}/typist --version"
  end
end
