# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veilig < Formula
  desc "veilig - Toy TLS certificate viewer"
  homepage "https://github.com/noqqe/veilig"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noqqe/veilig/releases/download/v1.8.0/veilig_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f2439b0208c03f292047f9f95dfa7b22e23d728d1a6c066ff9cc668ff292fe83"

      def install
        bin.install "veilig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noqqe/veilig/releases/download/v1.8.0/veilig_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c789f5bebd2e69a47fdf8d919594a205708d019e2c4476e4d16896e39cb20597"

      def install
        bin.install "veilig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/veilig/releases/download/v1.8.0/veilig_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "555964164325eb29c8bfa978a27956625f171b9544271277626672d63c48b3f6"
      def install
        bin.install "veilig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noqqe/veilig/releases/download/v1.8.0/veilig_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "09ddf0b783fc2deed69e17efae98d12447063690145fd23b4c49809374b58323"
      def install
        bin.install "veilig"
      end
    end
  end

  test do
    system "#{bin}/veilig --version"
  end
end
